### ISSUE TITLE
Create a demo application

### ISSUE THREAD

**Issue by krashish8** [Georepublic/pg_scheduleserv#12]
Create a demo application or an example of how to use the API using any frontend clients. How shall this application look like?

**Comment by dkastl** [comment]
Yes, this is a very good question ;-)

**Comment by dkastl** [comment]
Just as a reminder for myself: something that could be named a "Simulator" demo could be an alternative.

**Comment by krashish8** [comment]
Geoapify has a good frontend: https://www.geoapify.com/route-planner-api or https://apidocs.geoapify.com/playground/route-planner
